env:
  node: true
  es2021: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'github'
extends:
  - 'plugin:github/recommended'
rules: {}
