name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    environment: book-tid-api

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          touch .env 
          echo DO_BUCKET_ACCESS_KEY="${{secrets.DO_BUCKET_ACCESS_KEY}}" >> .env
          echo DO_BUCKET_NAME="${{secrets.DO_BUCKET_NAME}}" >> .env
          echo DO_BUCKET_SECRET_KEY="${{secrets.DO_BUCKET_SECRET_KEY}}" >> .env
          echo MONGO_URI_CONNECTION_STRING="${{secrets.TEST_MONGO_URI_CONNECTION_STRING}}" >> .env
          echo TEST_MONGO_URI_CONNECTION_STRING="${{secrets.TEST_MONGO_URI_CONNECTION_STRING}}" >> .env
          echo SENDGRID_API_KEY="${{secrets.SENDGRID_API_KEY}}" >> .env
          echo TEST_STRIPE_SECRET_KEY="${{secrets.TEST_STRIPE_SECRET_KEY}}" >> .env
          echo JWT_SECRET=testsecret >> .env
      - run: yarn
      - run: yarn test
      - run: yarn build

